[package]
name = "riprap"
version = "0.1.0"
authors = ["Darcy Jones <darcy.ab.jones@gmail.com>"]

[dependencies]
clap = "2.32.0"
rust-htslib = "0.21.0"
bio = "0.21.0"
failure = "0.1.2"
countrs = { git = "https://github.com/darcyabjones/countrs", branch = "master" }
windowrs = { git = "https://github.com/darcyabjones/windowrs", branch = "master" }
